ENVIRONMENT:
  MAX_EPISODE_STEPS: 10000
  
SIMULATOR:
  ACTION_SPACE_CONFIG: v0
  AGENT_0:
    RADIUS: 0.05
    SENSORS: [RGB_SENSOR_FRONT, RGB_SENSOR_LEFT, RGB_SENSOR_RIGHT, RGB_SENSOR_BACK, DEPTH_SENSOR_FRONT, DEPTH_SENSOR_LEFT, DEPTH_SENSOR_RIGHT, DEPTH_SENSOR_BACK]
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR_FRONT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    UUID: front
  RGB_SENSOR_LEFT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 1.5707963, 0]
    UUID: left
  RGB_SENSOR_RIGHT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, -1.5707963, 0]
    UUID: right
  RGB_SENSOR_BACK:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimRGBSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 3.1415926, 0]
    UUID: back
  DEPTH_SENSOR_FRONT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimDepthSensor
    POSITION: [0, 0.5, 0]
    UUID: depth_front
    NORMALIZE_DEPTH: False
    MIN_DEPTH: 0.1 
    MAX_DEPTH: 8.0
  DEPTH_SENSOR_LEFT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimDepthSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 1.5707963, 0] 
    UUID: depth_left
    NORMALIZE_DEPTH: False
    MIN_DEPTH: 0.1 
    MAX_DEPTH: 8.0
  DEPTH_SENSOR_RIGHT:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimDepthSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, -1.5707963, 0] 
    UUID: depth_right
    NORMALIZE_DEPTH: False
    MIN_DEPTH: 0.1 
    MAX_DEPTH: 8.0
  DEPTH_SENSOR_BACK:
    WIDTH: 720
    HEIGHT: 640
    HFOV: 110
    TYPE: HabitatSimDepthSensor
    POSITION: [0, 0.5, 0]
    ORIENTATION: [0, 3.1415926, 0] 
    UUID: depth_back
    NORMALIZE_DEPTH: False
    MIN_DEPTH: 0.1 
    MAX_DEPTH: 8.0

TASK:
  TYPE: Nav-v0
  SENSORS: []
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, GO_TOWARD_POINT]
  MEASUREMENTS: [TOP_DOWN_MAP_VLNCE]

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: YOUR_START_POSE_GZ
  SCENES_DIR: YOUR_SCENE_DIR